app/ext/courses/__init__.py
"""База данных курсов"""

__version__ = "0.1.0"
__author__ = "KLASSTRUEDA"

from .views import courses
from .views.user import user_courses
from .views.admin import admin_courses

bps = [(courses, "/courses"), (user_courses, "/lk/courses"), (admin_courses, "/admin/courses")]

app/ext/courses/views/admin.py
import werkzeug
from flask import Blueprint, current_app, flash, g, redirect, render_template, request, url_for
from flask_security import current_user, login_required

from app.ext.core.models import Photo, User
from app.ext.courses.forms import CategoryForm, CourseForm, ModuleForm, PromoForm, LessonForm, StudentWorkForm, ArtistWorkForm, ArtistForm, TariffForm
from app.ext.courses.models import Category, Course, Module, Lesson, StudentWork, Artist, ArtistWork, Tariff, Video, Promo, Payment
from app.extensions import db, photos, csrf, videos, files

from urllib.parse import urlparse, parse_qs

admin_courses = Blueprint("admin_courses", __name__, template_folder="templates")


@admin_courses.get("")
def index():
    g.breadcrumbs = [
        {"controller": "admin.index", "title": "Админка"},
        {"title": "Курсы"},
    ]
    categories_db = Category.query.all()
    courses_db = Course.query.all()
    modules_db = Module.query.all()
    lessons_db = Lesson.query.all()
    return render_template(
        "courses/admin/index.j2",
        categories=categories_db,
        courses=courses_db,
        modules=modules_db,
        lessons=lessons_db)


@admin_courses.route("/add-category", methods=["GET", "POST"])
def add_category():
    form = CategoryForm()

    if form.validate_on_submit():
        category_db = Category(
            title=form.data["title"],
            alias=form.data["alias"],
            description=form.data["description"],
        )
        filename=""
        # Обработка загруженных файлов
        if "photo" in request.files and request.files["photo"]:
            for file in request.files.getlist("photo"):
                if isinstance(file, werkzeug.datastructures.FileStorage) and file.filename:
                    filename = photos.save(file)
                    new_photo = Photo(
                        filename=filename,
                        alt=f'Изображение для {form.data["title"]}',
                    )
                    category_db.photos.append(new_photo)

        category_db.save()
        flash("Категория успешно добавлена!", "success")
        return redirect(url_for(".index"))

    return render_template("courses/admin/add-category.j2", form=form)


@admin_courses.route("/edit-category/<int:category_id>", methods=["GET", "POST"])
def edit_category(category_id):
    category_db = Category.query.get_or_404(category_id)
    form = CategoryForm(obj=category_db)

    if form.validate_on_submit():
        category_db.title = form.title.data
        category_db.alias = form.alias.data
        category_db.description = form.description.data

        # Обработка загруженных файлов
        if form.photo.data:
            for file in form.photo.data:
                if isinstance(file, werkzeug.datastructures.FileStorage) and file.filename:
                    filename = photos.save(file)
                    new_photo = Photo(
                        filename=filename,
                        alt=f'Изображение для {form.title.data}',
                    )
                    category_db.photos.append(new_photo)

        db.session.commit()
        flash("Категория успешно обновлена!", "success")
        return redirect(url_for(".edit_category", category_id=category_id))

    return render_template(
        "courses/admin/edit-category.j2",
        form=form,
        category=category_db,
        category_id=category_id)



@admin_courses.post("/delete-category/<int:category_id>")
def delete_category(category_id):
    category_db = Category.query.get_or_404(category_id)

    if category_db:
        db.session.delete(category_db)
        db.session.commit()
        flash("Категория успешно удалена!", "success")
    else:
        flash("Ошибка при удалении категории!", "danger")

    return redirect(url_for(".index"))


@admin_courses.route("/add-course", methods=["GET", "POST"])
def add_course():
    form = CourseForm()
    form.category_id.choices = [(category.id, category.title) for category in Category.query.all()]
    form.modules.choices = [(module.id, module.title) for module in Module.query.all()]

    if form.validate_on_submit():
        file_fields = [
        "preview_photo", "homepage_photo", "about_photo",
        "registration_photo", "artist_photo", "artist_photo_preview"
        ]

        # Проверяем, что все обязательные файлы загружены (кроме artist_photo_preview)
        if any(field not in request.files or not request.files[field].filename for field in file_fields if field != "artist_photo_preview"):
            flash("Все фото для курса обязательны к загрузке, кроме фото работы мастера.", "danger")
            return render_template(
                "courses/admin/add-course.j2",
                form=form,
                courses=Course.query.all(),
        )

        course_db = Course(
            category_id=form.data["category_id"],
            title=form.data["title"],
            alias=form.data["alias"],
            preview_description=form.data["preview_description"],
            show_on_homepage=form.data["show_on_homepage"],
            popular=form.data["popular"],
            level=form.data["level"],
            duration=form.data["duration"],
            about=form.data["about"],
            learning_process_title = form.data["learning_process_title"],
            learning_process_description=form.data["learning_process_description"],
            features_title=form.data["features_title"],
            features_description=form.data["features_description"],
            skills_title=form.data["skills_title"],
            skills_description=form.data["skills_description"],
            registration_form=form.data["registration_form"],
            artist_title=form.data["artist_title"],
            artist_description=form.data["artist_description"],
            price=form.data["price"],
            start_date=form.data["start_date"],
            end_date=form.data["end_date"],
        )

       # Загружаем файлы
        for field in file_fields:
            file = request.files.get(field)
            if file and file.filename:
                try:
                    filename = photos.save(file)
                    setattr(course_db, field, filename)
                except Exception as e:
                    flash(f"Ошибка при сохранении {field}: {e}", "danger")
                    return render_template(
                        "courses/admin/add-course.j2",
                        form=form,
                        courses=Course.query.all(),
                    )

        # добавление модулей
        selected_modules = Module.query.filter(Module.id.in_(form.modules.data)).all()
        course_db.modules.extend(selected_modules)

        course_db.save()
        flash("Курс успешно добавлен!", "success")
        return redirect(url_for(".index"))

    return render_template("courses/admin/add-course.j2", form=form)


@admin_courses.route("/edit-course/<int:course_id>", methods=["GET", "POST"])
def edit_course(course_id):
    course_db = Course.query.get_or_404(course_id)
    form = CourseForm(obj=course_db)  # Передаем объект course_db в форму для предзаполнения полей
    artists = course_db.artists
    form.category_id.choices = [(category.id, category.title) for category in Category.query.all()]
    form.modules.choices = [(module.id, module.title) for module in Module.query.all()]

    # Предзаполняем выбранные модули
    if request.method == "GET":
        form.modules.data = [module.id for module in course_db.modules]


    if form.validate_on_submit():

        course_db.category_id = form.category_id.data
        course_db.title = form.title.data
        course_db.alias = form.alias.data
        course_db.preview_description = form.preview_description.data
        course_db.show_on_homepage = form.show_on_homepage.data
        course_db.popular = form.popular.data
        course_db.level = form.level.data
        course_db.duration = form.duration.data
        course_db.about = form.about.data
        course_db.learning_process_title  = form.learning_process_title.data
        course_db.learning_process_description = form.learning_process_description.data
        course_db.features_title = form.features_title.data
        course_db.features_description = form.features_description.data
        course_db.skills_title = form.skills_title.data
        course_db.skills_description = form.skills_description.data
        course_db.registration_form = form.registration_form.data
        course_db.artist_title = form.artist_title.data
        course_db.artist_description = form.artist_description.data
        course_db.price = form.price.data
        course_db.start_date = form.start_date.data
        course_db.end_date = form.end_date.data

        file_fields = [
            "preview_photo", "homepage_photo", "about_photo",
            "registration_photo", "artist_photo", "artist_photo_preview"
        ]

        for field in file_fields:
            file = request.files.get(field)
            if file:
                filename = photos.save(file)
                setattr(course_db, field, filename)

        # Обработка загруженных файлов модулей
        course_db.modules = [Module.query.get(module_id) for module_id in form.modules.data]

        db.session.commit()
        flash("Курс успешно обновлен!", "success")
        return redirect(url_for(".edit_course", course_id=course_id))

     # Предзаполняем поля формы и фото
    form.preview_photo.data = course_db.preview_photo
    form.homepage_photo.data = course_db.homepage_photo
    form.about_photo.data = course_db.about_photo
    form.registration_photo.data = course_db.registration_photo
    form.artist_photo.data = course_db.artist_photo
    form.artist_photo_preview.data = course_db.artist_photo_preview

    preview_photo = course_db.preview_photo
    homepage_photo = course_db.homepage_photo
    about_photo = course_db.about_photo
    registration_photo = course_db.registration_photo

app/ext/courses/views/product.py
from datetime import datetime, timedelta

from flask import Blueprint, abort, g, redirect, render_template, request, url_for
from flask_security import hash_password
from jinja2.exceptions import TemplateNotFound
from sqlalchemy.exc import OperationalError

from app.ext.core.models import user_datastore
from app.extensions import csrf, db
from config import TZ

product = Blueprint("product", __name__, template_folder="templates")

@product.get
def index():
  pass

app/ext/courses/views/user.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_security import current_user

from app.ext.courses.models import Course, Payment
from app.extensions import csrf, db

user_courses = Blueprint("user_courses", __name__, template_folder="templates")


@user_courses.context_processor
def inject_user_menu():
    user_menu = [
        {"title": "Профиль", "href": "user.index"},
        {"title": "Курсы", "href": "user_courses.index"},
        {"title": "Баллы", "href": "user.points"},
        {"title": "Рассылка", "href": "user.mailing"},
        {"title": "Отзывы", "href": "user.feedback"},
    ]
    return {"user_menu": user_menu}


@user_courses.get("")
def index():
    payments_db = Payment.query.filter_by(user_id=current_user.id, status_payment=1).all() #получаем все оплаты пользователя со статусом 1
    return render_template("courses/user/user-courses.j2", payments=payments_db, active_item="user-courses")  # TODO: fix template name


@user_courses.get("/course/<int:course_id>")
def one(course_id):
    payment_db = Payment.query.filter_by(user_id=current_user.id, course_id=course_id).first_or_404()
    return render_template("courses/user/course-one.j2", payment=payment_db, active_item="course-one")


@user_courses.route("/proxy/<video_id>")
def proxy_video(video_id):
    # Перенаправляем на встраиваемый плеер YouTube
    return redirect(f'https://www.youtube.com/embed/{video_id}', code=302)

app/templates/courses/admin/add-artist.j2
{% extends "admin/base.j2" %}
{% from "macros/form.j2" import btn, input_form_6, input_form_12 %}

{% block admin_content %}
  <div class="container mb-4">
    <a href="{{ url_for('admin_courses.index') }}" class="btn btn-outline-primary">
      <i class="bi bi-arrow-left"></i> Назад
    </a>
  </div>
  <div class="container mb-4">
    <form action="{{ url_for('admin_courses.add_artist') }}" method="post" enctype="multipart/form-data">
    <h1>Добавление мастера</h1>
      <div class="row g-3">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        {{ input_form_6(form.user_id) }}
        {{ input_form_6(form.first_name) }}
        {{ input_form_6(form.last_name) }}
        {{ input_form_6(form.profession) }}
        {{ input_form_12(form.avatar) }}
        <label for="show_on_homepage">
          {{ form.show_on_homepage }} {{ form.show_on_homepage.label.text }}
        </label>
        {{ input_form_6(form.facebook) }}
        {{ input_form_6(form.instagram) }}
        {{ input_form_6(form.youtube) }}
        {{ input_form_6(form.vkontakte) }}
        {{ input_form_12(form.bio, style="height: 150px") }}
        {{ input_form_12(form.courses, style="height: 150px")}}
        {{ btn(form.submit, value="Отправить") }}
      </div>
    </form>
  </div>
  <div class="container mb-4">
    <h2>Список мастеров</h2>
    <ol>
      {% for artist in artists %}
        <li><a href="{{ url_for('admin_courses.edit_artist', artist_id=artist.id) }}">{{ artist.first_name }} {{ artist.last_name }}</a>
            <a href="{{ url_for('admin_courses.delete_artist', artist_id=artist.id) }}" onclick="return confirm('Вы уверены, что хотите удалить мастера?');">Удалить</a>
        </li>
      {% endfor %}
    </ol>
  </div>
  <div class="container mb-4">
    <a href="{{ url_for('admin_courses.index') }}" class="btn btn-outline-primary">
      <i class="bi bi-arrow-left"></i> Назад
    </a>
  </div>
{% endblock admin_content %}

app/templates/courses/admin/add-artistwork.j2
{% extends "admin/base.j2" %}
{% from "macros/form.j2" import btn, input_form_6, input_form_12 %}

{% block admin_content %}
  <div class="container mb-4">
    <a href="{{ url_for('admin_courses.index') }}" class="btn btn-outline-primary">
      <i class="bi bi-arrow-left"></i> Назад
    </a>
  </div>
  <div class="container mb-4">
    <form action="{{ url_for('admin_courses.add_artistwork') }}" method="post" enctype="multipart/form-data">
    <h1>Добавление работы мастера</h1>
      <div class="row g-3">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        {{ input_form_6(form.artist_id) }}
        {{ input_form_6(form.title) }}
        {{ input_form_12(form.description, style="height: 150px") }}
        {{ input_form_12(form.photo) }}
        {{ btn(form.submit, value="Отправить") }}
      </div>
    </form>
  </div>
  <div class="container mb-4">
    <h2>Список работ мастера</h2>
    <ol>
      {% for artistwork in artistworks %}
        <li><a href="{{ url_for('admin_courses.edit_artistwork', artistwork_id=artistwork.id) }}">{{ artistwork.title }} </a>
            <a href="{{ url_for('admin_courses.delete_artistwork', artistwork_id=artistwork.id) }}" onclick="return confirm('Вы уверены, что хотите удалить эту работу мастера?');">Удалить</a>
        </li>
      {% endfor %}
    </ol>
    <a href="{{ url_for('admin_courses.add_artistwork') }}" class="btn btn-outline-success">Добавить еще одну работу</a>
  </div>
  <div class="container mb-4">
    <a href="{{ url_for('admin_courses.index') }}" class="btn btn-outline-primary">
      <i class="bi bi-arrow-left"></i> Назад
    </a>
  </div>
{% endblock admin_content %}

app/templates/courses/admin/add-category.j2
{% extends "admin/base.j2" %}
{% from "macros/form.j2" import btn, input_form_6, input_form_12 %}

{% block admin_content %}
  <div class="container mb-4">
    <a href="{{ url_for('admin_courses.index') }}" class="btn btn-outline-primary">
      <i class="bi bi-arrow-left"></i> Назад
    </a>
  </div>
  <div class="container mb-4">
    <form action="{{ url_for('admin_courses.add_category') }}" method="post" enctype="multipart/form-data">
      <h1>Добавление категории</h1>
      <div class="row g-3">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        {{ input_form_6(form.title) }}
        {{ input_form_6(form.alias) }}
        {{ input_form_12(form.photo) }}
        {{ input_form_12(form.description, style="height: 150px") }}
        {{ btn(form.submit, value="Отправить") }}
      </div>
    </form>
  </div>
  <div class="container mb-4">
    <a href="{{ url_for('admin_courses.index') }}" class="btn btn-outline-primary">
      <i class="bi bi-arrow-left"></i> Назад
    </a>
  </div>
{% endblock admin_content %}

app/templates/courses/admin/add-course.j2
{% extends "admin/base.j2" %}
{% from "macros/form.j2" import btn, input_form_6, input_form_12 %}

{% block admin_content %}
  <div class="container mb-4">
    <a href="{{ url_for('admin_courses.index') }}" class="btn btn-outline-primary">
      <i class="bi bi-arrow-left"></i> Назад
    </a>
    <a class="btn btn-outline-primary" href="{{ url_for('admin_courses.help') }}">Инструкция по заполнению курса</a>
  </div>
  <div class="container mb-4">
    <form action="{{ url_for('admin_courses.add_course') }}" method="post" enctype="multipart/form-data">
      <h1>Добавление курса</h1>
      <p> Все фото, alias, а также дата начала и окончания курса, обязательны к заполнению.</p>
      <div class="row g-3">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        {{ input_form_6(form.category_id) }}
        {{ input_form_6(form.title) }}
        {{ input_form_6(form.alias) }}
        <h4>Карточка курса:</h4>
        {{ input_form_12(form.preview_description) }}
        {{ input_form_12(form.preview_photo) }}
        {{ input_form_12(form.level) }}
        {{ input_form_12(form.duration) }}
        {{ input_form_12(form.price) }}
        <h4>Показ курса на главной:</h4>
        <label for="show_on_homepage">
            {{ form.show_on_homepage }} {{ form.show_on_homepage.label.text }}
        </label>
        <label for="popular">
            {{ form.popular }} {{ form.popular.label.text }}
        </label>
        {{ input_form_12(form.homepage_photo) }}
        <h4>Описание курса на странице курса:</h4>
        {{ input_form_12(form.about, style="height: 150px") }}
        {{ input_form_12(form.about_photo) }}
        {{ input_form_12(form.learning_process_title) }}
        {{ input_form_12(form.learning_process_description, style="height: 150px") }}
        {{ input_form_12(form.features_title) }}
        {{ input_form_12(form.features_description, style="height: 150px",
        value='<div class="col-sm-6 wow fadeIn" data-wow-delay="0.1s">
              <div class="d-flex align-items-center mb-3">
                <div class="flex-shrink-0 btn-square bg-primary me-3">
                  <i class="fa fa-check text-white"></i>
                </div>
                <h5 class="mb-0">Творцам, которые хотят новое хобби</h5>
              </div>
              <span>Скучно сидеть в офисе и хочется делать что-то своими руками</span>
            </div>
            <div class="col-sm-6 wow fadeIn" data-wow-delay="0.2s">
              <div class="d-flex align-items-center mb-3">
                <div class="flex-shrink-0 btn-square bg-primary me-3">
                  <i class="fa fa-check text-white"></i>
                </div>
                <h5 class="mb-0">Дизайнерам и студентам</h5>
              </div>
              <span>Если вы уже знаете как делать украшения но не хватает навыков</span>
            </div>
            <div class="col-sm-6 wow fadeIn" data-wow-delay="0.3s">
              <div class="d-flex align-items-center mb-3">
                <div class="flex-shrink-0 btn-square bg-primary me-3">
                  <i class="fa fa-check text-white"></i>
                </div>
                <h5 class="mb-0">Сотрудникам ювелирных магазинов</h5>
              </div>
              <span>Вы лучше будете понимать как создавать ювелирные украшения и сможете сменить работу на более творческую</span>
            </div>
            <div class="col-sm-6 wow fadeIn" data-wow-delay="0.4s">
              <div class="d-flex align-items-center mb-3">
                <div class="flex-shrink-0 btn-square bg-primary me-3">
                  <i class="fa fa-check text-white"></i>
                </div>
                <h5 class="mb-0">Создателям бренда</h5>
              </div>
              <span>У вас уже есть свой бренд и вы хотите научиться новым навыкам для расширения линейки украшений</span>
            </div>',) }}
        {{ input_form_12(form.skills_title) }}
        {{ input_form_12(form.skills_description, style="height: 150px",
        value='<div class="col-lg-4 wow fadeIn" data-wow-delay="0.1s">
                  <div class="bg-white shadow d-flex align-items-center h-100 p-4" style="min-height: 150px;">
                    <div class="d-flex">
                      <div class="flex-shrink-0 btn-lg-square bg-primary">
                        <i class="fa fa-clock text-white"></i>
                      </div>
                      <div class="ps-4">
                        <h5>Сделаете свое оригинальное украшение</h5>
                        <span>в результате мастер-класса у вас будет новое кольцо - «всмятку»</span>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 wow fadeIn" data-wow-delay="0.1s">
                  <div class="bg-white shadow d-flex align-items-center h-100 p-4" style="min-height: 150px;">
                    <div class="d-flex">
                      <div class="flex-shrink-0 btn-lg-square bg-primary">
                        <i class="fa fa-clock text-white"></i>
                      </div>
                      <div class="ps-4">
                        <h5>Практические навыки</h5>
                        <span>Вы получите ценные навыки и знания, которые сможете применить в будущем для создания других украшений</span>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 wow fadeIn" data-wow-delay="0.1s">
                  <div class="bg-white shadow d-flex align-items-center h-100 p-4" style="min-height: 150px;">
                    <div class="d-flex">
                      <div class="flex-shrink-0 btn-lg-square bg-primary">
                        <i class="fa fa-clock text-white"></i>
                      </div>
                      <div class="ps-4">
                        <h5>Знания для дальнейшего развития</h5>
                        <span>Попробуете основные ювелирные операции и техники, и поймете понравится ли вам ювелирное дело</span>
                      </div>
                    </div>
                  </div>
                </div>',) }}
        <h4>Работы студентов:</h4>
        <p>Будут добавлены в карусель с работами студентов на страницу курса. Добавляем только в существущий курс.</p>
        <div class="col-12">
          <label>Работы студентов</label>
          <a href="{{ url_for('admin_courses.add_studentwork') }}" class="btn btn-outline-primary">Добавить работу студента</a>
        </div>
        <h4>Форма регистрации:</h4>
        <p> Форма, в которой пользователь может задать вопрос по курсу.</p>
        {{ input_form_12(form.registration_form, style="height: 150px") }}
        {{ input_form_12(form.registration_photo) }}
        <h4>Мастер:</h4>
        <p> Фото мастера будет на странице, фото работы - это небольшое фото к основному, будет вторым слоем.</p>
        {{ input_form_12(form.artist_photo) }}
        {{ input_form_12(form.artist_photo_preview) }}
        {{ input_form_12(form.artist_title)}}
        {{ input_form_12(form.artist_description, style="height: 150px") }}
        <h4>Работы мастера:</h4>
        <p>Будут добавлены в карусель под разделом мастера. Можно добавлять только в существущий курс.</p>
        <div class="col-12">
          <label>Работы мастера</label>
          <a href="{{ url_for('admin_courses.add_artistwork') }}" class="btn btn-outline-primary">Добавить работу мастера</a>
        </div>
        <h4>Дата начала/окончания курса</h4>
        <p>Обязательны к заполнению.</p>
        {{ input_form_12(form.start_date ) }}
        {{ input_form_12(form.end_date ) }}
        <h4>Модули</h4>
        <p>Можно добавить в курс уже существующие модули. Но если нужны новые модули - нужно сначала их создать и добавить уже в сохраненный курс.</p>
        {{ input_form_12(form.modules, style="height: 100px")}}
        {{ btn(form.submit, value="Отправить") }}
      </div>
    </form>
  </div>
  <div class="container mb-4">
    <a href="{{ url_for('admin_courses.index') }}" class="btn btn-outline-primary">
      <i class="bi bi-arrow-left"></i> Назад
    </a>
  </div>
{% endblock admin_content %}

app/templates/courses/admin/index.j2
{% extends "admin/base.j2" %}
{% from "macros/form.j2" import btn, input_form_6, input_form_12 %}

{% block admin_content %}
  <h3 class="mb-4">Управление курсами и контентом</h3>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{{ url_for('admin_courses.add_category') }}">Категории</a></li>
      <li class="breadcrumb-item"><a href="{{ url_for('admin_courses.add_course') }}">Добавление курса</a></li>
      <li class="breadcrumb-item"><a href="{{ url_for('admin_courses.add_module') }}">Модули</a></li>
      <li class="breadcrumb-item"><a href="{{ url_for('admin_courses.add_lesson') }}">Уроки</a></li>
      <li class="breadcrumb-item"><a href="{{ url_for('admin_courses.add_studentwork') }}">Работы студентов</a></li>
      <li class="breadcrumb-item"><a href="{{ url_for('admin_courses.add_artist') }}">Мастера</a></li>
      <li class="breadcrumb-item"><a href="{{ url_for('admin_courses.add_artistwork') }}">Работы мастеров</a></li>
      <li class="breadcrumb-item"><a href="{{ url_for('admin_courses.add_tariff') }}">Тарифы</a></li>
      <li class="breadcrumb-item"><a href="{{ url_for('admin_courses.add_promo') }}">Акции</a></li>
      <li class="breadcrumb-item"><a href="{{ url_for('admin_courses.save_selected_courses') }}">Курсы на главной</a></li>
      <li class="breadcrumb-item"><a href="{{ url_for('admin_courses.save_selected_artists') }}">Мастера на главной</a></li>
      <li class="breadcrumb-item"><a href="{{ url_for('admin_courses.save_selected_popular_courses') }}">Популярные курсы</a></li>
      <li class="breadcrumb-item"><a href="{{ url_for('admin_courses.help') }}">Инструкция по заполнению курса</a></li>
    </ol>
  </nav>
  {# <h3 class="mb-4">Список всех категорий курсов</h3> #}
  {% for category in categories %}
    {% if category.courses|length > 0 %}
      <div class="container mb-3">
        <div class="row justify-content-start">
          <div class="category-item mb-4">
            <div class="mb-3">
              Категория курса:
              <h4>
                <a href="{{ url_for('admin_courses.edit_category', category_id=category.id) }}">
                  {{ category.title }} - {{ category.alias }}
                </a>
              </h4>
              <form action="{{ url_for('admin_courses.delete_category', category_id=category.id) }}" method="post" style="display:inline;">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <button type="submit" class="btn btn-outline-secondary" onclick="return confirm('Вы уверены, что хотите удалить эту категорию?');">Удалить категорию</button>
              </form>
            </div>
          </div>
          <div class="row g-4">  {# g-4 — расстояние между колонками и рядами #}
            {% for course in category.courses %}
            <div class="col-sm-4">  {# или col-sm-6, col-lg-3 — зависит от желаемой плотности #}
              <div class="card">
                <a href="{{ url_for('admin_courses.edit_course', course_id=course.id) }}">
                  {% if course.preview_photo %}
                    {{ picture(
                      class_name='card-img-top',
                      file_name='upload/' ~ course.preview_photo,
                      alt='Изображение для курса %s' % course.title,
                      width=400,
                      height=400,
                      bp_tablet=834,
                      width_tablet=550,
                      height_tablet=550,
                      bp_desktop=1440,
                      width_desktop=600,
                      height_desktop=600
                    ) }}
                  {% endif %}
                  <div class="card-body p-3">
                    <h5 class="card-title">{{ course.title }}</h5>
                    <p class="card-text">{{ course.alias }}</p>
                    <p class="card-text">{{ course.preview_description }}</p>
                    <form action="{{ url_for('admin_courses.delete_course', course_id=course.id) }}" method="post" style="display:inline;">
                      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                      <button type="submit" class="btn btn-outline-secondary" onclick="return confirm('Вы уверены, что хотите удалить этот курс?');">Удалить курс</button>
                    </form>


                {% for module in course.modules %}
                  <div class="module-item">
                    <div class="mb-2">
                      модуль:
                      <a href="{{ url_for('admin_courses.edit_module', module_id=module.id) }}"><small>({{ module.id }})</small> {{ module.title }} - {{ module.alias }}</a>
                      <a href="{{ url_for('.delete_module', course_id=course.id, module_id=module.id) }}"
                        class="btn btn-outline-primary btn-sm"
                        onclick="return confirm('Вы уверены, что хотите удалить этот урок?');"
                        title="Удалить модуль">
                        <i class="bi bi-x"></i>
                      </a>
                    </div>
                    {% for lesson in module.lessons %}
                      <div class="module-item">
                        <div class="mb-2" style="padding-left: 90px">
                          урок:
                          <a href="{{ url_for('admin_courses.edit_lesson', lesson_id=lesson.id) }}"><small>({{ lesson.id }})</small> {{ lesson.title }} - {{ lesson.alias }}</a>
                          <a href="{{ url_for('.delete_lesson', lesson_id=lesson.id) }}"
                            class="btn btn-outline-secondary btn-sm"
                            onclick="return confirm('Вы уверены, что хотите удалить этот урок?');"
                            title="Удалить урок">
                            <i class="bi bi-x"></i>
                          </a>
                        </div>
                      </div>
                    {% endfor %}
                  </div>
                {% endfor %}
                </div>
                </a>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    {% endif %}
  {% endfor %}

{% endblock admin_content %}