app/ext/core/views/__init__.py
import time
from datetime import datetime, timedelta

from flask import Blueprint, abort, current_app, g, flash, redirect, render_template, request, url_for
from flask_security import hash_password, current_user
from jinja2.exceptions import TemplateNotFound
from sqlalchemy.exc import OperationalError

from app.ext.core.models import user_datastore
from app.extensions import csrf, db
from config import TZ
from app.ext.core.forms import FeedbackForm
from app.ext.courses.models import Course, Artist
from app.ext.courses.forms import CoursePaymentForm

from app.utils import send_to_telegram, send_to_email


core = Blueprint("core", __name__, template_folder="templates")


def init_request():
    """Создание базовых ролей и пользователей."""
    try:
        user_datastore.find_or_create_role(
            name="admin",
            permissions={"admin-read", "admin-write", "user-read", "user-write"},
        )
        user_datastore.find_or_create_role(name="user", permissions={"user-read", "user-write"})
        if not user_datastore.find_user(email="admin@z-gu.ru"):
            user_datastore.create_user(
                username="admin",
                email="admin@z-gu.ru",
                password=hash_password("1234567"),
                roles=["admin"],
            )
        if not user_datastore.find_user(email="user@z-gu.ru"):
            user_datastore.create_user(
                username="user",
                email="user@z-gu.ru",
                password=hash_password("1234567"),
                roles=["user"],
            )
        db.session.commit()
    except OperationalError as msg:
        abort(500, msg)


@core.before_app_request
def before_app_request():
    g.current_year = datetime.now(tz=TZ).year
    g.menu = [
      {
        "title": "Главная",
        "href": "",
      }, {
        "title": "О нас",
        "href": "about",
      }, {
        "title": "Курсы",
        "view_function": "course.index"
      }, {
        "title": "Разделы",
        "href": "#",
        "submenu": [
          {
            "title": "Наша команда",
            "href": "team",
          }, {
            "title": "Преимущества",
            "href": "feature",
          }, {
              "title": "FAQ",
              "href": "faq",
          }, {
            "title": "Оплата",
            "view_function": "course.payment"
          }, {
            "title": "Отзывы",
            "href": "testimonial",
          }, {
              "title": "Юридическая информация",
              "href": "legal-info",
          },{
              "title": "Политика конфиденциальности",
              "href": "privacy",
          },
        ],
      }, {
        "title": "Контакты",
        "href": "contacts",
      }
    ]
    g.contacts = {
      "phone": "+7(911)245-40-00",
      "tel": "+79112454000",
      "address": "Санкт-Петербург, Газовая 10",
      "email": "klasstrueda@gmail.com",
    }
    g.social_links = [{
      "title": "facebook-f",
      "href": "https://www.facebook.com/klasstrueda",
    }, {
      "title": "youtube",
      "href": "https://www.youtube.com/channel/UCXIbv2Y_Qvy3sxvluUDA6XQ",
    },{
      "title": "vk",
      "href": "https://vk.com/true_da",
    }, {
      "title": "instagram",
      "href": "https://www.instagram.com/klasstrueda/",
    }]


@core.get("")
def index():
    """Главная страница."""
    init_request()
    if current_user.is_authenticated:
        form = FeedbackForm(
            first_name=current_user.first_name,
            email=current_user.email,
            meta={"csrf": False})
    else:
        form = FeedbackForm(meta={"csrf": False})
    featured_artists = Artist.query.filter_by(show_on_homepage=True).all()
    featured_courses = Course.query.filter_by(show_on_homepage=True).all()
    return render_template(
        "public/index.j2",
        form=form,
        hide_header=True,
        featured_artists=featured_artists,
        featured_courses=featured_courses,
        active_item="")


@core.get("/<string:page_name>")
def page(page_name):
    """Для других статических страниц."""
    try:
        return render_template(f"public/{page_name}.j2", active_item=page_name)
    except TemplateNotFound:
        abort(404)


@core.get("/contacts")
def contacts():
    """Контакты."""
    init_request()
    if current_user.is_authenticated:
        form = FeedbackForm(
            first_name=current_user.first_name,
            email=current_user.email,
            meta={"csrf": False})
    else:
        form = FeedbackForm(meta={"csrf": False})
    return render_template("public/contacts.j2", form=form, active_item="contacts")


@core.get("/basic-jewelry")
def basic_jewelry():
    """Базовый ювелирный курс."""
    init_request()
    if current_user.is_authenticated:
        form = FeedbackForm(
            first_name=current_user.first_name,
            email=current_user.email,
            meta={"csrf": False})
    else:
        form = FeedbackForm(meta={"csrf": False})
    return render_template("public/basic-jewelry.j2", form=form, active_item="basic-jewelry")


@core.get("/appointment")
def appointment():
    """Регистрация на курс."""
    init_request()
    if current_user.is_authenticated:
        form = FeedbackForm(
            first_name=current_user.first_name,
            email=current_user.email,
            meta={"csrf": False})
    else:
        form = FeedbackForm(meta={"csrf": False})
    return render_template("public/appointment.j2", form=form, active_item="appointment")


@core.get("/jewelry-marathon")
def jewelry_marathon():
    """Регистрация на курс."""
    init_request()
    if current_user.is_authenticated:
        form = FeedbackForm(
            first_name=current_user.first_name,
            email=current_user.email,
            meta={"csrf": False})
    else:
        form = FeedbackForm(meta={"csrf": False})
    return render_template("public/jewelry-marathon.j2", form=form, active_item="jewelry-marathon")


@core.get("/jewelry-ring")
def jewelry_ring():
    """Регистрация на курс."""
    init_request()
    form = FeedbackForm(request.form, meta={"csrf": False})
    return render_template("public/jewelry-ring.j2", form=form, active_item="jewelry-ring")


@core.get("/about")
def about():
    """О нас."""
    init_request()
    featured_artists = Artist.query.filter_by(show_on_homepage=True).all()
    return render_template("public/about.j2", featured_artists=featured_artists, active_item="about")


@core.route("/thank-you")
def thank_you():
    course_id = request.args.get("course_id")  # Извлекаем course_id из query параметров
    course = Course.query.get(course_id) if course_id else None
    return render_template("public/thank_you.j2", course=course)



@core.route("/form-processing", methods=["GET", "POST"])
def form_proc():
    if current_user.is_authenticated:
        form = FeedbackForm(
            first_name=current_user.first_name,
            email=current_user.email
        )
    else:
        form = FeedbackForm(request.form)

    if form.validate_on_submit():
        # Проверка Honeypot поля
        if form.hidden_field.data:
            current_app.logger.warning("Honeypot triggered! Possible bot detected.")
            flash("Ошибка при отправке формы. Попробуйте снова.", "danger")
            return redirect(url_for("course.contacts"))

        # Проверка временной метки
        form_time = int(form.form_time.data)  # Получаем значение времени в миллисекундах
        current_time = int(time.time() * 1000)  # Текущее время в миллисекундах
        time_difference = current_time - form_time

        if time_difference < 2000:  # Если разница меньше 2 секунд
            current_app.logger.warning("Форма отправлена слишком быстро! Возможный бот.")
            flash("Ошибка при отправке формы. Попробуйте снова.", "error")
            return redirect(url_for("course.form_payment"))

        first_name = form.first_name.data
        email = form.email.data
        course_title = form.course_title.data
        message = form.message.data

        # Формируем сообщение для отправки уведомления
        send_message = (
            f"Новый вопрос с сайта:\n"
            f"Имя: {first_name}\n"
            f"Email: {email}\n"
            f"Сообщение: {message}"
        )

        # Отправляем сообщение админу в Телеграм
        send_to_telegram(send_message, send_to_admin=True)

         # Отправка уведомления админу по email
        email_subject = "Новый вопрос с сайта"
        send_to_email(
            subject=email_subject,
            body=send_message,
            recipients=['bogatyrevata@gmail.com'],
            sender='klasstruedaru@gmail.com',
            reply_to=['klasstruedaru@gmail.com']
        )

        # Отправка подтверждения пользователю
        user_subject = "Спасибо за ваш вопрос!"
        user_body = (
            f"Здравствуйте, {first_name}!\n\n"
            "Спасибо, что написали нам.\n"
            "Мы получили ваш вопрос и свяжемся с вами в ближайшее время.\n\n"
            "С уважением,\n"
            "Команда Klasstrueda"
        )
        send_to_email(
            subject=user_subject,
            body=user_body,
            recipients=[email],
            sender='klasstruedaru@gmail.com',
            reply_to=['klasstruedaru@gmail.com']
        )

        flash("Спасибо за ваш вопрос! Мы свяжемся с вами в ближайшее время. Ответ придёт на указанную вами почту.", "success")
        return redirect(url_for("core.thank_you"))

    return render_template("public/contacts.j2", form=form, active_item="form-processing")

app/templates/base.j2
{%- from "macros/picture.j2" import picture -%}
{%- from "macros/generate_page_header.j2" import generate_page_header -%}
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ site_name }}</title>

  <meta name="description" content="{{ meta_description }}">

  <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='img/icons/apple-touch-icon.png') }}">
  <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/icons/favicon-32x32.png') }}">
  <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/icons/favicon-16x16.png') }}">
  <link rel="manifest" href="{{ url_for('static', filename='img/icons/site.webmanifest') }}">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">

  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">

  <link rel="stylesheet" href="{{ url_for('static', filename='css/animate.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.carousel.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.min.css') }}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lite-youtube-embed/0.3.3/lite-yt-embed.css"> <!-- библиотека Lite YouTube Embed для показа видео по ссылке -->

  <!-- Yandex.Metrika counter -->
  <script type="text/javascript" >
    (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
    m[i].l=1*new Date();
    for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
    k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
    (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

    ym(39783150, "init", {
          clickmap:true,
          trackLinks:true,
          accurateTrackBounce:true,
          webvisor:true
    });
  </script>
  <noscript><div><img src="https://mc.yandex.ru/watch/39783150" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
  <!-- /Yandex.Metrika counter -->
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-CHZLDDER15"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-CHZLDDER15');
  </script>
  <!-- /Google tag (gtag.js) -->
</head>
<body>
  {% include "header.j2" %}
  {% if not hide_header %}
    {{ generate_page_header(is_admin=is_admin) }}
  {% endif %}
  {# flash уведомления #}
  <div class="container">
    {% with messages = get_flashed_messages(with_categories=True) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Закрыть"></button>
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
  </div>
  {% block content %}{% endblock content %}
  {% include "footer.j2" %}
  <script src="{{ url_for('static', filename='js/jquery-3.7.1.min.js')}}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js')}}"></script>
  <script src="{{ url_for('static', filename='js/wow.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/easing.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/waypoints.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/owl.carousel.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/script.min.js') }}"></script>
  <!-- Скрипт Lite YouTube Embed для показа видео по ссылке -->
  <script defer src="https://cdnjs.cloudflare.com/ajax/libs/lite-youtube-embed/0.3.3/lite-yt-embed.js"></script>
  {% block js %}{% endblock js %}
</body>
</html>

app/templates/footer.j2
<!-- Footer Start -->
<div class="container-fluid bg-dark text-light footer my-6 mb-0 py-6 wow fadeIn" data-wow-delay="0.1s">
  <div class="container">
    <div class="row g-5">
      <div class="col-lg-3 col-md-6">
        <h4 class="text-white mb-4">Контакты</h4>
        <a class="" href="{{ url_for('core.index') }}"><h2 class="text-primary mb-4">Klasstrueda</h2></a>
        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>
          <a href="https://t.me/gutovda" target="_blank" class="btn btn-sm btn-outline-info">
            Написать в Telegram
          </a>
          </p>
        {# <p class="mb-2"><i class="fa fa-envelope me-3"></i>{{ g.contacts.email }}</p> #}
      </div>
      <div class="col-lg-3 col-md-6">
        <h4 class="text-light mb-4">Разделы сайта</h4>
        <a class="btn btn-link" href="{{ url_for('core.page', page_name='about') }}">О мастерской</a>
        <a class="btn btn-link" href="{{ url_for('core.page', page_name='contacts') }}">Контакты</a>
        <a class="btn btn-link" href="{{ url_for('core.page', page_name='faq') }}">FAQ</a>
        <a class="btn btn-link" href="{{ url_for('core.page', page_name='legal-info') }}">Юридическая информация</a>
        <a class="btn btn-link" href="{{ url_for('core.page', page_name='privacy') }}">Политика конфиденциальности</a>
      </div>
      <div class="col-lg-3 col-md-6">
        <h4 class="text-light mb-4">Популярные</h4>
         {% for course in g.popular_courses %}
          <a class="btn btn-link" href="{{ url_for('course.course_details', course_id=course.id) }}">{{ course.title }}</a>
         {% endfor %}
        <a class="btn btn-link" href="{{ url_for('core.page', page_name='testimonial') }}">Отзывы</a>
        <a class="btn btn-link" href="{{ url_for('course.payment') }}">Оплата</a>
      </div>
      <div class="col-lg-3 col-md-6">
        <h4 class="text-light mb-4">Рассылка полезного</h4>
        <form action="">
          <div class="input-group">
            <input type="text" class="form-control p-3 border-0" placeholder="Введите email">
            <button class="btn btn-primary">Подписаться</button>
          </div>
        </form>
        <h6 class="text-white mt-4 mb-3">Мы в соцсетях</h6>
        <div class="d-flex pt-2">
          {% for link in g.social_links %}
            <a class="btn btn-square btn-outline-light me-{% if not loop.last %}1{% else %}0{% endif %}"
            href="{{ link.href }}"
            target="_blank">
              <i class="fab fa-{{ link.title }}"></i>
            </a>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Footer End -->

<!-- Copyright Start -->
<div class="container-fluid copyright text-light py-4 wow fadeIn" data-wow-delay="0.1s">
  <div class="container">
    <div class="row">
      <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
        &copy; <a href="{{ url_for('core.index') }}">Klasstrueda</a>, все права защищены.
      </div>
      <div class="col-md-6 text-center text-md-end">
        Разработано: <a href="https://github.com/bogatyrevata">Taisiiya Bogatyreva</a>
        <br>При участии: <a href="https://jokerinteractive.ru/" target="_blank">JokerTeam</a>
      </div>
    </div>
  </div>
</div>
<!-- Copyright End -->

<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

app/templates/header.j2
{% from "macros/make_menu.j2" import make_menu %}

<!-- Spinner Start -->
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
  <div class="spinner-grow text-primary" role="status"></div>
</div>
<!-- Spinner End -->

<!-- Topbar Start -->
<div class="container-fluid bg-dark text-light p-0">
  <div class="row gx-0 d-none d-lg-flex">
    <div class="col-lg-7 px-5 text-start">
    </div>
    <div class="col-lg-5 px-5 text-end">
      <div class="h-100 d-inline-flex align-items-center me-4">
        <a href="https://t.me/gutovda" target="_blank" class="btn btn-sm btn-outline-info">
          <small class="fa fa-phone-alt text-primary me-2"></small>
          Telegram
        </a>
      </div>
      <div class="h-100 d-inline-flex align-items-center mx-n2">
        {% for link in g.social_links %}
          <a class="{% if not loop.last %}btn btn-square btn-link rounded-0 border-0 border-end border-secondary{% else %}btn btn-square btn-link rounded-0{% endif %}"
          href="{{ link.href }}"
          target="_blank">
            <i class="fab fa-{{ link.title }} text-primary"></i>
          </a>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<!-- Topbar End -->

<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top p-0">
  <a class="navbar-brand d-flex align-items-center border-end px-4 px-lg-5" href="{{ url_for('core.index') }}">
    <h2 class="m-0">Klasstrueda</h2>
  </a>
  <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <div class="navbar-nav ms-auto p-4 p-lg-0">
      {{ make_menu(g.menu, page) }}
    </div>
      {% if not current_user.is_authenticated %}
      <a href="{{ url_for('security.login') }}" class="btn btn-primary py-4 px-lg-5 d-lg-block">Войти
      <i class="fa fa-arrow-right ms-3"></i></a>
      <a href="{{ url_for('security.register') }}" class="btn btn-primary py-4 px-lg-5 d-lg-block">Регистрация
      </a>
    {% else %}
      <a href="{{ url_for('user.index') }}" class="btn btn-primary py-4 px-lg-5 d-lg-block">Личный кабинет
      <i class="fa fa-arrow-right ms-3"></i></a>
      <a href="{{ url_for('security.logout') }}" class="btn btn-primary py-4 px-lg-5 d-lg-block">Выйти
      <i class="fa fa-arrow-right ms-3"></i></a>
    {% endif %}
  </div>
</nav>
<!-- Navbar End -->